// ignore_for_file: non_constant_identifier_names

import 'package:emilyretailerapp/Model/Entity.dart';

class PromotionEntity extends Entity {
  late String address;
  late String buttonLabel;
  late String categoryCode;
  late double dist = 0.0;
  late String favourite;
  late String latitude;
  late String longitude;
  late String offerEndDate;
  late String offerId;
  late String offerShortDescription;
  late String offerStartDate;
  late String offerType;
  late String offerUrl;
  late String partnerClass;
  late String partnerImage;
  late String partnerName;
  late String partnerWebsite;
  late String phoneNumber;
  late String phoneType;
  late String urlSuffix;
  late String imgBackUrl;
  late String imgFrontUrl;
  late String redeem_value;
  late int reward_points;
  late int rewards_value;
  late List<dynamic> locationsArray;
  late dynamic randomBuy;
  late dynamic date_time;
  late String partnerID;
  late String storeLocationID;
  late String restriction;
  late String time_stamp;
  late dynamic utcDateTime;
  late dynamic transaction_type;
  late String sun_open_status;
  late String sun_start_time;
  late String sun_end_time;
  late String mon_open_status;
  late String mon_start_time;
  late String mon_end_time;
  late String tue_open_status;
  late String tue_start_time;
  late String tue_end_time;
  late String wed_open_status;
  late String wed_start_time;
  late String wed_end_time;
  late String thu_open_status;
  late String thu_start_time;
  late String thu_end_time;
  late String fri_open_status;
  late String fri_start_time;
  late String fri_end_time;
  late String sat_open_status;
  late String sat_start_time;
  late String sat_end_time;

  late String transactionCount;
  late String transactionLastDate;
  late List<dynamic> rules;

  late double offerPrice = 3.0;
  late int quantityLimit = 3;

  late String promotiontype;
  late String savedCashBack;
  late String earnedPoints;
  late String earnedStamp;
  late String totalTransaction;
  late String transactionRewardType;
  late String transactionRewardValue;
  late String transactionRewards;
  late String receiverName;
  late String senderName;
  late String cardType;
  late String newCardImageUrl;
  late String cardName;
  late String oldCardName;
  late String oldCardDescription;
  late String oldCardImageUrl;
  late String cardLastPrice;
  late String cardDisplayPrice;
  late List<dynamic> catalogsData;
  late String orderNo;
  late String ordertotalBeforeTax;
  late String orderGratuityPrice;
  late String gratuityPercentage;
  late String standardShippingCost;
  late String freeShippingAmount;
  late String orderTotalTax;
  late String orderTotalPrice;
  late String orderReferenceNo;
  late String orderReceiptNo;
  late String orderRdeemValue;
  late String creditApplied;
  late String paymentCardNo;
  late String paymentCardName;

  late String orderDispatchStatus;
  late Map<String, dynamic> expressData = {};
  late String cellBackgroundColor;
  late String cashDiscountAmount;
  late String cashDiscountPercentage;
  late String giftCardsAppliedValue;
  late String couponAppliedValue;
  late String couponCode;
  late List<dynamic> appliedCouponsArray;

  PromotionEntity();

  PromotionEntity.fromjson(Map<String, dynamic> json) {
    address = json["address"];
    buttonLabel = json["button_label"];
    categoryCode = json["category_code"];
    dist = json["dist"];
    favourite = json["favourite"];
    latitude = json["latitude"];
    longitude = json["longitude"];
    offerEndDate = json["offer_endDate"];
    offerId = json["offer_id"];
    offerShortDescription = json["offer_short_description"];
    offerStartDate = json["offer_startDate"];
    offerType = json["offer_type"];
    offerUrl = json["offer_url"];
    partnerClass = json["partner_class"];
    partnerImage = json["partner_image"];
    partnerName = json["partner_name"];
    partnerWebsite = json["partner_website"];
    phoneNumber = json["phone_number"];
    phoneType = json["phone_type"];
    urlSuffix = json["url_suffix"];
    imgBackUrl = json["offer_image_back_url"];
    imgFrontUrl = json["offer_image_front_url"];
    redeem_value = json["redeem_value"];
    reward_points = json["reward_points"];
    rewards_value = json["rewards_value"];
    locationsArray = json["locations"];
    partnerID = json["partner_id"];
    storeLocationID = json["store_location_id"];
    restriction = json["restriction"];
    sun_open_status = json["sun_open_status"];
    sun_start_time = json["sun_start_time"];
    sun_end_time = json["sun_end_time"];
    mon_open_status = json["mon_open_status"];
    mon_start_time = json["mon_start_time"];
    mon_end_time = json["mon_end_time"];
    tue_open_status = json["tue_open_status"];
    tue_start_time = json["tue_start_time"];
    tue_end_time = json["tue_end_time"];
    wed_open_status = json["wed_open_status"];
    wed_start_time = json["wed_start_time"];
    wed_end_time = json["wed_end_time"];
    thu_open_status = json["thu_open_status"];
    thu_start_time = json["thu_start_time"];
    thu_end_time = json["thu_end_time"];
    fri_open_status = json["fri_open_status"];
    fri_start_time = json["fri_start_time"];
    fri_end_time = json["fri_end_time"];
    sat_open_status = json["sat_open_status"];
    sat_start_time = json["sat_start_time"];
    sat_end_time = json["sat_end_time"];

    rules = [];
    final rulesArray = json["rules"];
    for (var rule in rulesArray) {
      rules.add(rule);
    }

    transactionCount = json["transaction_count"];
    transactionLastDate = json["transaction_last_date"];
    receiverName = json["receiverName"];
    senderName = json["buyerName"];
    cardType = json["cardType"];
    newCardImageUrl = json["cardImageUrl"];
    oldCardImageUrl = json["oldCardImageUrl"];
    oldCardDescription = json["oldCardDescription"];
    cardName = json["cardDescription"];
    oldCardName = json["oldCardName"];
    cardLastPrice = json["cardLastPrice"];
    cardDisplayPrice = json["cardDisplayPrice"];

    orderNo = json["cardDisplayPrice"];
    ordertotalBeforeTax = json["cardDisplayPrice"];
    orderTotalTax = json["cardDisplayPrice"];
    orderTotalPrice = json["cardDisplayPrice"];
    orderReferenceNo = json["cardDisplayPrice"];
    orderRdeemValue = json["cardDisplayPrice"];
    creditApplied = json["cardDisplayPrice"];
    paymentCardNo = json["cardDisplayPrice"];
    paymentCardName = json["cardDisplayPrice"];
    earnedStamp = json["earnedStamp"];
    orderReceiptNo = json["serverUUID"];
    utcDateTime = json["utcDateTime"];
    orderDispatchStatus = json["orderDispatchStatus"];
    orderGratuityPrice = json["gratuity"];
    gratuityPercentage = json["gratuityPercentage"];
    standardShippingCost = json["standardShippingCost"];
    freeShippingAmount = json["freeShippingAmount"];
    expressData = json["expressData"];
    cellBackgroundColor = json["cellBackgroundColor"];
    cashDiscountAmount = json["cashDiscountAmount"];
    cashDiscountPercentage = json["cashDiscountPercentage"];
    giftCardsAppliedValue = json["giftCardsAppliedValue"];
  }
}
